package com.ugk.pi.attention

/** The host implements this with its own UI. The SDK does not create an overlay window. */
fun interface UrgentMessagePresenter {
    suspend fun show(message: UrgentMessage): UrgentPresentation
}

/** Opt in only after the host can route control events back to the original Agent session. */
interface InteractiveUrgentMessagePresenter : UrgentMessagePresenter

data class UrgentMessage(
    val title: String,
    val body: String,
    val reason: String,
    val accent: UrgentAccent = UrgentAccent.AMBER,
    val blocks: List<UrgentContentBlock> = emptyList(),
    val actions: List<UrgentAction> = emptyList(),
    val form: UrgentForm? = null,
    /** Generated by the SDK tool, never accepted from model arguments. */
    val binding: UrgentPresentationBinding? = null
)

data class UrgentAction(val id: String, val label: String)

/** One plain-text answer field. The host fixes the input length and submission behavior. */
data class UrgentForm(
    val id: String,
    val label: String,
    val placeholder: String,
    val submitLabel: String
)

data class UrgentPresentationBinding(val presentationId: String, val sessionId: String)

/** A bounded presentation vocabulary. Hosts may render it in their own visual language. */
enum class UrgentAccent { AMBER, GREEN, BLUE, RED }

enum class UrgentBlockType { HEADING, PARAGRAPH, CALLOUT, BULLET }

data class UrgentContentBlock(val type: UrgentBlockType, val text: String)

enum class UrgentPresentationStatus {
    SHOWN,
    PERMISSION_DENIED,
    BUSY,
    UNAVAILABLE,
    FAILED
}

data class UrgentPresentation(val status: UrgentPresentationStatus)
